name = "ada_code"
description = "version definitiva del codigo en Ada del tfg"
version = "0.1.0-dev"

authors = ["APR"]
maintainers = ["APR <example@example.com>"]
maintainers-logins = ["github-username"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
gnatprove = "^14.1.1"
